### ISSUE TITLE
KeyError: 'NV'

### ISSUE THREAD

**Issue by sugizo** [MineralsCloud/pgm#23]
**environment**
google colab

**steps**
```
!pip install -U phonon-gas-model
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/casio3.yaml
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/feo.yaml
```

**execute**
`!pgm run casio3.yaml`

**result**
```
  _ __   __ _ _ __ ___  
 | '_ \ / _` | '_ ` _ \ 
 | |_) | (_| | | | | | |
 | .__/ \__, |_| |_| |_|
 | |     __/ |          
 |_|    |___/           
 Version 1.0.0-a
    
Traceback (most recent call last):
  File "/usr/local/bin/pgm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 93, in main
    run(settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 16, in run
    user_settings.read_from_yaml(file_settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/settings.py", line 76, in read_from_yaml
    self.NV = dic['NV']
KeyError: 'NV'
```

**execute**
`!pgm run feo.yaml`

**result**
```
  _ __   __ _ _ __ ___  
 | '_ \ / _` | '_ ` _ \ 
 | |_) | (_| | | | | | |
 | .__/ \__, |_| |_| |_|
 | |     __/ |          
 |_|    |___/           
 Version 1.0.0-a
    
Traceback (most recent call last):
  File "/usr/local/bin/pgm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 93, in main
    run(settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 16, in run
    user_settings.read_from_yaml(file_settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/settings.py", line 76, in read_from_yaml
    self.NV = dic['NV']
KeyError: 'NV'
```

best regards

**Comment by underhill1886** [comment]
Hi, I just saw this. I will dig into it ASAP.

**Comment by underhill1886** [comment]
Hi,
In order to use the code, you need to download all other files in the example folder as well.
Your wget commands only download the `.yaml` file, which is only part of the input.
Best regards

**Comment by sugizo** [comment]
already download all the examples files 
got different error from first post

**steps**
```
!pip install -U phonon-gas-model
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/casio3.yaml
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/1500K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/2000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/2500K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/3000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/3500K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/casio3/4000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/feo.yaml
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/0K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/1000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/2000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/3000K.txt
!wget -c https://github.com/MineralsCloud/pgm/blob/master/examples/feo/4000K.txt
```

**execute**
`!pgm run casio3.yaml`

**result**
```
  _ __   __ _ _ __ ___  
 | '_ \ / _` | '_ ` _ \ 
 | |_) | (_| | | | | | |
 | .__/ \__, |_| |_| |_|
 | |     __/ |          
 |_|    |___/           
 Version 1.0.0-a
    
Traceback (most recent call last):
  File "/usr/local/bin/pgm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 93, in main
    run(settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 16, in run
    user_settings.read_from_yaml(file_settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/settings.py", line 74, in read_from_yaml
    dic = yaml.load(f, Loader=Loader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 688, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "casio3.yaml", line 207, column 75
```

**execute**
`!pgm run feo.yaml`

**result**
```
  _ __   __ _ _ __ ___  
 | '_ \ / _` | '_ ` _ \ 
 | |_) | (_| | | | | | |
 | .__/ \__, |_| |_| |_|
 | |     __/ |          
 |_|    |___/           
 Version 1.0.0-a
    
Traceback (most recent call last):
  File "/usr/local/bin/pgm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 93, in main
    run(settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/cli/main.py", line 16, in run
    user_settings.read_from_yaml(file_settings)
  File "/usr/local/lib/python3.10/dist-packages/pgm/settings.py", line 74, in read_from_yaml
    dic = yaml.load(f, Loader=Loader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 688, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "feo.yaml", line 207, column 75
```

**Comment by underhill1886** [comment]
Hi,

Your wget command only downloads an HTML view of that file.

You should use the github raw files instead.

Also, save all input files into one folder and run pgm inside that folder.

```
!mkdir casio3
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/casio3.yaml -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/1500K.txt -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/2000K.txt -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/2500K.txt -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/3000K.txt -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/3500K.txt -P ./casio3/
!wget -c https://raw.githubusercontent.com/MineralsCloud/pgm/master/examples/casio3/4000K.txt -P ./casio3/
```

then

```
%cd casio3
!pgm run casio3.yaml
```
Best regards
